---
- name: Delete old sshd_config ('kevin.conf')
  file:
    path: /etc/ssh/sshd_config.d/kevin.conf
    state: absent

- name: Add sshd_config - local user 'kevin'
  copy:
    src: /opt/.ansible/roles/sshd/files/lusr/kevin.conf
    dest: /etc/ssh/sshd_config.d/lusr-kevin.conf
    owner: root
    group: root
    mode: u=rw,go-rwx
  notify: Reload sshd