- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        cache_valid_time: 604800
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/ansible.yml
    - include: tasks/ssh-server.yml
    - include: tasks/bashrc.yml
    - include: tasks/nanorc.yml
    - include: tasks/unattended_upgrades.yml
    - include: tasks/cron.yml
