---
- name: Create local user (ansible)
  include_tasks: tasks/ansible/create.yaml

- name: Create local user (kevin)
  include_tasks: tasks/kevin/create.yaml
  when:
    - lusr.kevin is defined
    - lusr.kevin | bool

- name: Delete local user (kevin)
  include_tasks: tasks/kevin/remove.yaml
  when:
    - lusr.kevin is defined
    - not lusr.kevin