- name: user 'ansible' - present
  user:
    name: ansible
    system: yes
    local: yes
    home: "/root/.ansible/pull/{{ ansible_fqdn }}"
    create_home: no
    group: ansible
    shell: /sbin/nologin

- name: user 'ansible' - sudoers
  copy:
    src: files/sudoers/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: user 'ansible' - authorized_keys
  authorized_key:
    user: ansible
    key: https://github.com/kevtx-bot.keys
    exclusive: yes

- name: Add 'sshd_config.d/lusr--ansible.conf'
  copy:
    src: files/ssh-server/lusr--ansible.conf
    dest: /etc/ssh/sshd_config.d/lusr--ansible.conf
    owner: root
    group: root
    mode: u=rw,go=r

- name: Reload 'sshd' systemd service
  systemd:
    state: reloaded
    name: sshd.service