- name: Ansible group
  group:
    name: ansible
    system: yes
    state: present

- name: Ansible user
  user:
    name: ansible
    shell: /sbin/nologin
    home: /root/.ansible/pull
    create_home: no
    group: ansible
    groups: ''
    system: yes
    state: present

- name: Ansible user (sudoers)
  copy:
    src: files/sudoers/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Ansible user (authorized_keys)
  authorized_key:
    user: ansible
    key: https://raw.githubusercontent.com/kevtx/ansible-pull/auto-cron/tasks/ansible-user/authorized_keys
    exclusive: yes

- name: Ansible user (ssh_config.d)
  copy:
    src: files/ssh-server/local--user_ansible.conf
    dest: /etc/ssh/sshd_config.d/local--user_ansible.conf
    owner: root
    group: root
    mode: u=rw,go=r

- name: Reload 'sshd' systemd service
  systemd:
    state: reloaded
    name: sshd.service