---
- copy:
    src: files/*.crt
    dest: /usr/local/share/ca-certificates/
    mode: a=r

- apt:
    name: ca-certificates
    state: present
    cache_valid_time: 604800

- shell: /usr/sbin/update-ca-certificates
