- name: Install cron job [ git.kevtx.com/kevtx/ansible-pull:auto-cron ]
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/15"
    job: "/usr/bin/ansible-pull -o -U https://git.kevtx.com/kevtx/ansible-pull -C auto-cron > /dev/null"
