---
- set_fact:
    node_exporter_target: "1.3.1"

- name: Create group 'prometheus'
  group:
    name: prometheus
    state: present

- name: Create system user 'prometheus'
  user:
    name: prometheus
    group: prometheus
    createhome: no
    system: yes
    shell: /sbin/nologin
    state: present

- name: Create dir '/opt/prometheus'
  file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: u=rwx,o-rwx

- name: Install node_exporter service .env file
  copy:
    src: node_exporter.env
    dest: /opt/prometheus/node_exporter.env
    owner: prometheus
    group: prometheus
    mode: u=rw,go-rwx

- stat:
    path: /usr/bin/node_exporter
  register: binary

- name: Check node_exporter version
  shell: node_exporter --version
  register: result
  when: binary.stat.exists

- set_fact:
    node_exporter_installed: "{{ result.stdout | regex_search('(?<=version\\s).+(?=\\s.branch)')}}"
  when: binary.stat.exists

- name: Download node_exporter tarball
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_target }}/node_exporter-{{ node_exporter_target }}.linux-amd64.tar.gz
    dest: /opt/prometheus
  when: not binary.stat.exists or
        (binary.stat.exists and node_exporter_installed < node_exporter_target)

- name: Extract node_exporter tarball
  unarchive:
    remote_src: yes
    src: /opt/prometheus/node_exporter-{{ node_exporter_target }}.linux-amd64.tar.gz
    dest: /opt/prometheus
  when: not binary.stat.exists or
        (binary.stat.exists and node_exporter_installed < node_exporter_target)

- name: Create symlink ('/usr/bin/node_exporter')
  file:
    src: /opt/prometheus/node_exporter-{{ node_exporter_target }}.linux-amd64/node_exporter
    path: /usr/bin/node_exporter
    state: link
    owner: prometheus
    group: prometheus
    mode: u=rx,go-rwx
  when: not binary.stat.exists or
        (binary.stat.exists and node_exporter_installed < node_exporter_target)

- name: Make binary executable ('/usr/bin/node_exporter')
  file:
    path: /usr/bin/node_exporter
    state: link
    owner: prometheus
    group: prometheus
    mode: u=rx,go-rwx

- name: Check /opt/prometheus ownership
  file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Install node_exporter systemd service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Configure node_exporter systemd service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service
