---
- name: Delete local user 'kevin' 
  user:
    name: kevin
    state: absent

- name: Delete '/home/kevin' 
  file:
    path: /home/kevin
    state: absent

- name: Delete local group 'kevin' 
  group:
    name: kevin
    state: absent

- name: Deleting /etc/ssh/sshd_config.d/{kevin.conf,lusr-kevin.conf}
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/ssh/sshd_config.d/kevin.conf"
    - "/etc/ssh/sshd_config.d/lusr-kevin.conf"