---
- name: Download node_exporter tarball
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_target }}/node_exporter-{{ node_exporter_target }}.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: Extract node_exporter tarball
  unarchive:
    remote_src: yes
    src: /opt/prometheus/node_exporter-{{ node_exporter_target }}.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: Create symlink ('/usr/bin/node_exporter')
  file:
    src: /opt/prometheus/node_exporter-{{ node_exporter_target }}.linux-amd64/node_exporter
    path: /usr/bin/node_exporter
    state: link
    owner: prometheus
    group: prometheus
    mode: u=rx,go-rwx