---
- name: Add sshd_config - Enable PAM (kevtx.lan)
  copy:
    dest: /etc/ssh/sshd_config.d/kevtx.lan--enable_pam.conf
    src: /opt/.ansible/roles/sshd/files/kevtx.lan/enable_pam.conf
    owner: root
    group: root
    mode: u=r,go-rwx
  when:
    - domain_kevtx.join | bool
  notify: Reload sshd

- name: Add sshd_config - Allow SSH key (kevtx.lan)
  copy:
    dest: /etc/ssh/sshd_config.d/kevtx.lan-grp_allow_key.conf
    src: /opt/.ansible/roles/sshd/files/kevtx.lan/grp_allow_key.conf
    owner: root
    group: root
    mode: u=r,go-rwx
  when:
    - domain_kevtx.join | bool
    - not (domain_kevtx.join and domain_kevtx.no__grp_allow_key is defined)
  notify: Reload sshd

- name: Remove sshd_config - Allow SSH key (kevtx.lan)
  file:
    path: /etc/ssh/sshd_config.d/kevtx.lan-grp_allow_key.conf
    state: absent
  when:
    - not domain_kevtx.join or
      (domain_kevtx.join | bool and domain_kevtx.no__grp_allow_key is defined and domain_kevtx.no__grp_allow_key | bool)
  notify: Reload sshd

- name: Add sshd_config - Allow SSH password (kevtx.lan)
  copy:
    dest: /etc/ssh/sshd_config.d/kevtx.lan-grp_allow_pwd.conf
    src: /opt/.ansible/roles/sshd/files/kevtx.lan/grp_allow_pwd.conf
    owner: root
    group: root
    mode: u=r,go-rwx
  when:
    - domain_kevtx.join | bool
    - not (domain_kevtx.join and domain_kevtx.no__grp_allow_pwd is defined)
  notify: Reload sshd

- name: Remove sshd_config - Allow SSH password (kevtx.lan)
  file:
    path: /etc/ssh/sshd_config.d/kevtx.lan-grp_allow_pwd.conf
    state: absent
  when:
    - not domain_kevtx.join or 
      (domain_kevtx.join | bool and domain_kevtx.no__grp_allow_pwd is defined and domain_kevtx.no__grp_allow_pwd | bool)
  notify: Reload sshd
