---
  - name: /etc/bash.bashrc
    copy:
      src: files/etc.bashrc
      dest: /etc/bash.bashrc
      owner: root
      group: root
      mode: 0444

  - name: /etc/skel/.bashrc
    copy:
      src: files/skel.bashrc
      dest: /etc/skel/.bashrc
      owner: root
      group: root
      mode: 0600