---
- include_tasks: unattended-upgrades.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- include_tasks: nanorc.yaml

- include_tasks: bashrc.yaml

- include_tasks: packages.yaml
  when: ansible_facts['os_family']|lower == 'debian'