---
- name: Install dependencies
  apt: 
    name: openssh-server
    state: latest
    cache_valid_time: 604800

- name: Set sshd_config.d folder permissions
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: u=rx,go-rwx

- name: Add base sshd_config boilerplate
  copy:
    dest: /etc/ssh/sshd_config
    src: /opt/.ansible/roles/sshd/files/base.conf
    owner: root
    group: root
    mode: u=r,go-rwx

- name: Install sshd configs (kevtx.lan)
  include_tasks: /opt/.ansible/roles/sshd/tasks/kevtx.lan/install.yaml
  when:
    - domain_kevtx.join is defined
    - domain_kevtx.join | bool

- name: Remove sshd configs (kevtx.lan)
  include_tasks: /opt/.ansible/roles/sshd/tasks/kevtx.lan/remove-all.yaml
  when:
    - domain_kevtx.join is not defined or
      not domain_kevtx.join
